### ISSUE TITLE
Add tzdata in order to change timezone

### ISSUE THREAD

**Issue by niko2** [alexanderschnitzler/docker-mysqldump#3]
adding tzdata to your Dockerfile could allow to change the timezone, which is very helpful for cron !

**Comment by alexanderschnitzler** [comment]
Hi @niko2,
would you mind creating a pull request or explain any further what exactly you mean?

Thanks in advance.
Alex

**Comment by niko2** [comment]
#4

**Comment by pd5200** [comment]
FROM alpine:latest

RUN apk add --no-cache mysql-client \
            tzdata && \
            cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime &&\
            echo "Asia/Shanghai" > /etc/timezone  &&\
            apk del tzdata
ENTRYPOINT ["crond", "-f"]
